# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logf_z_given_A <- function(zs, A, pis, Ps) {
    .Call('_banyan_logf_z_given_A', PACKAGE = 'banyan', zs, A, pis, Ps)
}

logf_z_given_A_single <- function(zs, A, pis, Ps) {
    .Call('_banyan_logf_z_given_A_single', PACKAGE = 'banyan', zs, A, pis, Ps)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call('_banyan_rdirichlet_cpp', PACKAGE = 'banyan', num_samples, alpha_m)
}

update_P <- function(A, zs, K0, b10, b20) {
    .Call('_banyan_update_P', PACKAGE = 'banyan', A, zs, K0, b10, b20)
}

update_P_single <- function(A, zs, K0, b10, b20) {
    .Call('_banyan_update_P_single', PACKAGE = 'banyan', A, zs, K0, b10, b20)
}

update_counts <- function(zs, K0) {
    .Call('_banyan_update_counts', PACKAGE = 'banyan', zs, K0)
}

update_z <- function(zs, A, Ps, pis, classes) {
    .Call('_banyan_update_z', PACKAGE = 'banyan', zs, A, Ps, pis, classes)
}

update_z_single <- function(zs, A, Ps, pis, classes) {
    .Call('_banyan_update_z_single', PACKAGE = 'banyan', zs, A, Ps, pis, classes)
}

